/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.32.0-1-g4892df653 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.32.0-1-g4892df653"
#endif
#define SDL_REVISION_NUMBER 0
